# Default values for operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

dorisOperator:
  # the namespace of dorisoperator, if not set, the release namespace will be used.
  namespace: "doris"
  image:
    repository: selectdb/doris.k8s-operator
    tag: 1.3.1
    # imagePullSecrets:
    #  - name: imagePullSecret

  # Map of nodeSelectors to match when scheduling pods on nodes
  nodeSelector: {}
    # kubernetes.io/arch: amd64
    # kubernetes.io/os: linux
    # app.kubernetes.node.name: "k8s-node1"

  # node affinity for operator pod scheduling.
  nodeAffinity: {}
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #     nodeSelectorTerms:
  #       - matchFields:
  #           - key: metadata.name
  #             operator: In
  #             values:
  #               - target-host-name