name: docker
on:
  push:
    tags: "*.*.*"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: selectdb/doris.k8s-operator

      - name: Doris Debug meta
        id: debug_meta
        uses: docker/metadata-action@v5
        with:
          images: selectdb/doris-debug-ubuntu

      - name: env 
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        env:
          Version: ${{ steps.vars.outputs.tag }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        env:
          Version: ${{ steps.vars.outputs.tag }}
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
      - name: Build debug and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile_doris_debug
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.debug_meta.outputs.tags }}
